[package]
name = "ownership"
version = "0.1.0"
authors = ["S-b-E <105817+S-b-E@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
